# Generated by Django 6.0.4 on 2026-06-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0010_cptblmovcompleto290526_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movpos',
            name='fecha_vacancia',
            field=models.CharField(blank=True, db_column='FECHA VACANCIA', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movposhistorico',
            name='fecha_vacancia',
            field=models.CharField(blank=True, db_column='FECHA VACANCIA', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movposstaging',
            name='fecha_vacancia',
            field=models.CharField(blank=True, db_column='FECHA VACANCIA', max_length=255, null=True),
        ),
    ]
