# Generated by Django 6.0.4 on 2026-06-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0011_movpos_fecha_vacancia_movposhistorico_fecha_vacancia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuadroVacancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('ocupadas_permanente', models.IntegerField(default=0)),
                ('ocupadas_eventual', models.IntegerField(default=0)),
                ('ocupadas_total', models.IntegerField(default=0)),
                ('vacantes_permanente', models.IntegerField(default=0)),
                ('vacantes_eventual', models.IntegerField(default=0)),
                ('vacantes_total', models.IntegerField(default=0)),
                ('total_permanente', models.IntegerField(default=0)),
                ('total_eventual', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cuadro Vacancia',
                'verbose_name_plural': 'Cuadros Vacancia',
                'db_table': 'cuadro_vacancia',
            },
        ),
    ]
