# Generated by Django 6.0.4 on 2026-06-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0012_cuadrovacancia'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movpos',
            index=models.Index(fields=['f_efva', 'fecha_captura'], name='idx_movpos_fefva_fcap'),
        ),
        migrations.AddIndex(
            model_name='plantilla1800plazas',
            index=models.Index(fields=['of_de_solicitud', 'nivel'], name='idx_p1800_ofsol_niv'),
        ),
        migrations.AddIndex(
            model_name='plantilla1800plazas',
            index=models.Index(fields=['nivel'], name='idx_p1800_nivel'),
        ),
    ]
