# Generated by Django 6.0.4 on 2026-06-20 07:09

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0013_movpos_idx_movpos_fefva_fcap_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bajassig',
            index=models.Index(fields=['posicion'], name='idx_baj_posicion'),
        ),
        migrations.AddIndex(
            model_name='bajassig',
            index=models.Index(fields=['fecha_efectiva'], name='idx_baj_fefec'),
        ),
        migrations.AddIndex(
            model_name='bajassig',
            index=models.Index(django.db.models.functions.text.Trim('motivo_descr'), name='idx_baj_t_motdes'),
        ),
        migrations.AddIndex(
            model_name='bajassig',
            index=models.Index(django.db.models.functions.text.Trim('accion_descr'), name='idx_baj_t_accdes'),
        ),
        migrations.AddIndex(
            model_name='empleadoscompletossig',
            index=models.Index(fields=['nivel'], name='idx_emp_nivel'),
        ),
        migrations.AddIndex(
            model_name='empleadoscompletossig',
            index=models.Index(fields=['estado_nomina'], name='idx_emp_estnom'),
        ),
        migrations.AddIndex(
            model_name='empleadoscompletossig',
            index=models.Index(django.db.models.functions.text.Trim('nivel'), name='idx_emp_t_nivel'),
        ),
        migrations.AddIndex(
            model_name='empleadoscompletossig',
            index=models.Index(django.db.models.functions.text.Trim('estado_nomina'), name='idx_emp_t_estnom'),
        ),
        migrations.AddIndex(
            model_name='movpos',
            index=models.Index(django.db.models.functions.text.Trim('estado_psn'), name='idx_mp_t_estpsn'),
        ),
        migrations.AddIndex(
            model_name='movpos',
            index=models.Index(django.db.models.functions.text.Trim('motivo'), name='idx_mp_t_motivo'),
        ),
        migrations.AddIndex(
            model_name='movpos',
            index=models.Index(django.db.models.functions.text.Trim('unidad_adva'), name='idx_mp_t_unidadv'),
        ),
    ]
