# Generated by Django 6.0.4 on 2026-06-20 15:59

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0014_bajassig_idx_baj_posicion_bajassig_idx_baj_fefec_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bajassigstaging',
            index=models.Index(fields=['posicion'], name='idx_bajs_posicion'),
        ),
        migrations.AddIndex(
            model_name='bajassigstaging',
            index=models.Index(fields=['fecha_efectiva'], name='idx_bajs_fefec'),
        ),
        migrations.AddIndex(
            model_name='bajassigstaging',
            index=models.Index(django.db.models.functions.text.Trim('motivo_descr'), name='idx_bajs_t_motdes'),
        ),
        migrations.AddIndex(
            model_name='bajassigstaging',
            index=models.Index(django.db.models.functions.text.Trim('accion_descr'), name='idx_bajs_t_accdes'),
        ),
        migrations.AddIndex(
            model_name='empleadoscompletossigstaging',
            index=models.Index(fields=['nivel'], name='idx_emps_nivel'),
        ),
        migrations.AddIndex(
            model_name='empleadoscompletossigstaging',
            index=models.Index(fields=['estado_nomina'], name='idx_emps_estnom'),
        ),
        migrations.AddIndex(
            model_name='empleadoscompletossigstaging',
            index=models.Index(django.db.models.functions.text.Trim('nivel'), name='idx_emps_t_nivel'),
        ),
        migrations.AddIndex(
            model_name='empleadoscompletossigstaging',
            index=models.Index(django.db.models.functions.text.Trim('estado_nomina'), name='idx_emps_t_estnom'),
        ),
        migrations.AddIndex(
            model_name='movposstaging',
            index=models.Index(fields=['f_efva', 'fecha_captura'], name='idx_mps_fefva_fcap'),
        ),
        migrations.AddIndex(
            model_name='movposstaging',
            index=models.Index(django.db.models.functions.text.Trim('estado_psn'), name='idx_mps_t_estpsn'),
        ),
        migrations.AddIndex(
            model_name='movposstaging',
            index=models.Index(django.db.models.functions.text.Trim('motivo'), name='idx_mps_t_motivo'),
        ),
        migrations.AddIndex(
            model_name='movposstaging',
            index=models.Index(django.db.models.functions.text.Trim('unidad_adva'), name='idx_mps_t_unidadv'),
        ),
    ]
