# Generated by Django 6.0.4 on 2026-07-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0018_add_tuvo_insubsistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovPosLatest',
            fields=[
                ('no_pos_actual', models.CharField(db_column='Nº Pos Actual', max_length=255, primary_key=True, serialize=False)),
                ('mov_pos_id', models.BigIntegerField(db_column='id')),
                ('estado_psn', models.CharField(blank=True, db_column='Estado Psn', db_index=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'MOV_POS_LATEST',
                'managed': True,
            },
        ),
    ]
