# Generated by Django 6.0.4 on 2026-07-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0021_add_auditoria_catptofunc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatNivelJerarquicoPlaza',
            fields=[
                ('plaza', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nivel_jerarquico', models.SmallIntegerField(blank=True, editable=False, null=True)),
                ('descripcion_nivel_jerarquico', models.CharField(blank=True, choices=[('Titular de la Agencia Nacional de Aduanas de México', '0 — Titular de la Agencia Nacional de Aduanas de México'), ('Director General', '1 — Director General'), ('Director Central', '2 — Director Central'), ('Director', '3 — Director'), ('Titular de Aduana', '3 — Titular de Aduana'), ('Subdirector', '4 — Subdirector'), ('Jefe de Departamento', '5 — Jefe de Departamento'), ('Enlace', '6 — Enlace'), ('Operativo de Confianza', '7 — Operativo de Confianza'), ('Operativo de Base', '8 — Operativo de Base')], max_length=255, null=True)),
                ('nvl_direc_origen', models.CharField(blank=True, help_text="Referencia informativa: valor de 'Nvl Direc' en MOV_POS al momento de sincronizar.", max_length=255, null=True)),
                ('modificado_por', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'cat_nivel_jerarquico_plaza',
                'managed': True,
            },
        ),
        # Django no tiene un campo ENUM nativo; el CreateModel de arriba deja
        # `descripcion_nivel_jerarquico` como VARCHAR(255). Se convierte a
        # ENUM real de MySQL con las 10 descripciones del catálogo de negocio
        # (pedido explícito: "en mysql debera ser un enum"). reverse_sql
        # regresa a VARCHAR(255) si se hace rollback.
        migrations.RunSQL(
            sql="""
                ALTER TABLE cat_nivel_jerarquico_plaza
                MODIFY COLUMN descripcion_nivel_jerarquico ENUM(
                    'Titular de la Agencia Nacional de Aduanas de México',
                    'Director General',
                    'Director Central',
                    'Director',
                    'Titular de Aduana',
                    'Subdirector',
                    'Jefe de Departamento',
                    'Enlace',
                    'Operativo de Confianza',
                    'Operativo de Base'
                ) NULL;
            """,
            reverse_sql="""
                ALTER TABLE cat_nivel_jerarquico_plaza
                MODIFY COLUMN descripcion_nivel_jerarquico VARCHAR(255) NULL;
            """,
        ),
    ]
