# Generated by Django 6.0.4 on 2026-07-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0022_add_cat_nivel_jerarquico_plaza'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelJerarquicoPrioridadConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(blank=True, choices=[('nivel_jerarquico', 'Nivel Jerárquico (asignación manual)'), ('nvl_direc_origen', 'Nvl Direc (referencia MOV_POS)')], max_length=20, null=True)),
                ('modificado_por', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'cat_nivel_jerarquico_prioridad',
                'managed': True,
            },
        ),
    ]
