# Generated by Django 6.0.4 on 2026-07-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0025_add_auditoria_organigrama_anam'),
    ]

    operations = [
        migrations.AddField(
            model_name='organigramaanam',
            name='subordinados',
            field=models.TextField(blank=True, help_text='Códigos de departamento (subordinados directos) separados por coma, calculados con la misma lógica de organigrama_tree.build_parent_map.', null=True),
        ),
    ]
