# Generated by Django 6.0.4 on 2026-07-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0026_add_subordinados_organigrama_anam'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlineacionOrganizacionalHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('porcentaje_alineacion_general', models.DecimalField(decimal_places=1, max_digits=5)),
                ('total_activas', models.IntegerField(default=0)),
                ('total_alineadas', models.IntegerField(default=0)),
                ('total_con_diferencias', models.IntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ALINEACION_ORGANIZACIONAL_HISTORICO',
                'ordering': ['fecha'],
                'managed': True,
            },
        ),
    ]
