# Generated by Django 6.0.4 on 2026-07-13 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0027_alineacionorganizacionalhistorico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CeldaOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(choices=[('EMPLEADOS_COMPLETOS_SIG', 'Empleados'), ('BAJAS_SIG', 'Bajas'), ('MOV_POS', 'Movimientos Posición'), ('CP_TBL_HISTORIAL', 'Histórico Movimientos')], max_length=64)),
                ('clave_negocio', models.JSONField()),
                ('clave_negocio_hash', models.CharField(db_index=True, max_length=64)),
                ('columna', models.CharField(max_length=128)),
                ('valor_original', models.TextField(null=True)),
                ('valor_nuevo', models.TextField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tabla', 'clave_negocio_hash', 'columna', 'activo'], name='plantilla_c_tabla_132f07_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('tabla', 'clave_negocio_hash', 'columna'), name='uniq_override_activo')],
            },
        ),
    ]
