# Generated by Django 6.0.7 on 2026-07-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0028_celdaoverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganigramaAnamSig',
            fields=[
                ('departamento', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('descripcion_larga', models.CharField(max_length=500)),
                ('nivel_direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('unidad_negocio', models.CharField(max_length=255)),
                ('unidad_administrativa', models.CharField(max_length=255)),
                ('doaf', models.CharField(max_length=255)),
                ('num_posicion_gerente', models.CharField(max_length=255)),
                ('posicion_director', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ORGANIGRAMA_ANAM_SIG',
            },
        ),
        # `isSIGInfo` ya existe físicamente en ORGANIGRAMA_ANAM (tabla legacy
        # adoptada, ver 0024_adopt_organigrama_anam.py) — un compañero agregó
        # el campo al modelo sin generar su propia migración, dejando el
        # historial de Django desincronizado (makemigrations lo detecta recién
        # ahora). Se registra aquí como SOLO estado (sin DDL real) para que
        # `migrate`/`makemigrations` dejen de proponer un ALTER TABLE que
        # fallaría por columna duplicada — mismo patrón que la adopción
        # original de esta tabla. No cambia ningún comportamiento existente.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='organigramaanam',
                    name='isSIGInfo',
                    field=models.BooleanField(default=False),
                ),
            ],
            database_operations=[],
        ),
    ]
