# Generated by Django 6.0.7 on 2026-07-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0029_organigramaanamsig'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadoFotoAlias',
            fields=[
                ('numempleado', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'EMPLEADO_FOTO_ALIAS',
            },
        ),
    ]
