# Generated by Django 6.0.7 on 2026-07-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0030_empleadofotoalias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadofotoalias',
            name='numempleado',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
