# Generated by Django 6.0.7 on 2026-07-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0031_alter_empleadofotoalias_numempleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatCodigoPosicion',
            fields=[
                ('plaza', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cat_codigo_posicion',
                'managed': True,
            },
        ),
    ]
