# Generated by Django 6.0.7 on 2026-07-28 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0032_add_cat_codigo_posicion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TblColumnasPlantillaQuincenal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(db_index=True, max_length=20)),
                ('columna', models.CharField(max_length=100)),
                ('valor', models.TextField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='columnas_quincenal_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_columnas_plantilla_quincenal',
                'managed': True,
                'indexes': [models.Index(fields=['posicion'], name='tbl_columna_posicio_86c450_idx')],
                'unique_together': {('posicion', 'columna')},
            },
        ),
    ]
