# Generated by Django 6.0.7 on 2026-07-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0033_add_tbl_columnas_plantilla_quincenal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblcolumnasplantillaquincenal',
            old_name='fecha_modificacion',
            new_name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='tblcolumnasplantillaquincenal',
            name='modificado_por',
        ),
        migrations.AlterField(
            model_name='celdaoverride',
            name='tabla',
            field=models.CharField(choices=[('EMPLEADOS_COMPLETOS_SIG', 'Empleados'), ('BAJAS_SIG', 'Bajas'), ('MOV_POS', 'Movimientos Posición'), ('CP_TBL_HISTORIAL', 'Histórico Movimientos'), ('PLANTILLA_QUINCENAL', 'Columnas Quincenal (Plantilla Detalle)')], max_length=64),
        ),
    ]
