# Generated by Django 6.0.7 on 2026-07-29 21:03

from django.db import migrations, models


def migrar_codigos_a_correccion(apps, schema_editor):
    """Copia cat_codigo_posicion (plaza, codigo) a cat_correccion_posicion
    como (posicion, columna='codigo', valor) antes de borrar la tabla vieja —
    centraliza Código junto con Tipo de Aduana/DG de Aduana compactada en un
    solo catálogo de solo lectura."""
    CatCodigoPosicion = apps.get_model('plantilla', 'CatCodigoPosicion')
    CatCorreccionPosicion = apps.get_model('plantilla', 'CatCorreccionPosicion')

    CatCorreccionPosicion.objects.bulk_create(
        [
            CatCorreccionPosicion(posicion=row.plaza, columna='codigo', valor=row.codigo)
            for row in CatCodigoPosicion.objects.all()
        ],
        batch_size=1000,
    )


def revertir_migracion_codigos(apps, schema_editor):
    """No-op: CatCodigoPosicion ya no existe al revertir esta migración
    (se recrea después, sin datos) — recargar con `cargar_correcciones_plantilla`
    si se necesita revertir de verdad."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0034_quincenal_baseline_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatCorreccionPosicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(db_index=True, max_length=20)),
                ('columna', models.CharField(max_length=100)),
                ('valor', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cat_correccion_posicion',
                'managed': True,
            },
        ),
        migrations.RunPython(migrar_codigos_a_correccion, revertir_migracion_codigos),
        migrations.DeleteModel(
            name='CatCodigoPosicion',
        ),
        migrations.AddIndex(
            model_name='catcorreccionposicion',
            index=models.Index(fields=['posicion'], name='cat_correcc_posicio_c6e5e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='catcorreccionposicion',
            unique_together={('posicion', 'columna')},
        ),
    ]
