# Generated by Django 6.0.7 on 2026-07-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0035_centralizar_correcciones_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='catcorreccionposicion',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='catcorreccionposicion',
            name='modificado_por',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
