# Generated by Django 6.0.4 on 2026-08-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0038_datos_personales'),
    ]

    operations = [
        migrations.AddField(
            model_name='zafirobitacora',
            name='registros_datos_personales',
            field=models.IntegerField(default=0),
        ),
    ]
