# Generated by Django 6.0.4 on 2026-08-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0039_datos_personales_bitacora_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celdaoverride',
            name='tabla',
            field=models.CharField(choices=[('EMPLEADOS_COMPLETOS_SIG', 'Empleados'), ('BAJAS_SIG', 'Bajas'), ('MOV_POS', 'Movimientos Posición'), ('CP_TBL_HISTORIAL', 'Histórico Movimientos'), ('PLANTILLA_QUINCENAL', 'Columnas Quincenal (Plantilla Detalle)'), ('DATOS_PERSONALES', 'Datos Personales')], max_length=64),
        ),
    ]
