# Generated by Django 6.0.4 on 2026-08-04 23:52
#
# `Conmutador` ya existe físicamente en DATOS_PERSONALES / _HISTORICO /
# _STAGING (varchar(255), agregada fuera de Django junto con `extension` en
# su momento — ver comentario en plantilla.models.DatosPersonalesBase). El
# AddField es solo de ESTADO (SeparateDatabaseAndState, database_operations
# vacío): si se dejara como AddField normal, Django intentaría
# `ALTER TABLE ... ADD COLUMN Conmutador ...` y fallaría por columna
# duplicada. `extension` sí necesita ALTER real: pasa de varchar(255) a JSON
# nativo (MySQL) para poder guardar `[{"extension": ..., "area": ...}, ...]`
# en personas con más de una extensión (ver Directorio ANAM).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0040_alter_celdaoverride_tabla'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='datospersonales',
                    name='conmutador',
                    field=models.CharField(blank=True, db_column='Conmutador', max_length=255, null=True),
                ),
                migrations.AddField(
                    model_name='datospersonaleshistorico',
                    name='conmutador',
                    field=models.CharField(blank=True, db_column='Conmutador', max_length=255, null=True),
                ),
                migrations.AddField(
                    model_name='datospersonalesstaging',
                    name='conmutador',
                    field=models.CharField(blank=True, db_column='Conmutador', max_length=255, null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='extension',
            field=models.JSONField(blank=True, db_column='extension', null=True),
        ),
        migrations.AlterField(
            model_name='datospersonaleshistorico',
            name='extension',
            field=models.JSONField(blank=True, db_column='extension', null=True),
        ),
        migrations.AlterField(
            model_name='datospersonalesstaging',
            name='extension',
            field=models.JSONField(blank=True, db_column='extension', null=True),
        ),
    ]
