# Generated by Django 6.0.4 on 2026-08-07 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0041_datos_personales_conmutador_extension_json'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuscripcionNotificacionPosicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(db_index=True, max_length=20)),
                ('tipo', models.CharField(choices=[('VACANTE', 'Vacante'), ('OCUPACION', 'Ocupación')], max_length=10)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('estado_conocido_al_suscribir', models.CharField(choices=[('O', 'Ocupada'), ('V', 'Vacante')], max_length=1)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('notificado_en', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones_posicion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SUSCRIPCION_NOTIFICACION_POSICION',
                'indexes': [models.Index(fields=['posicion', 'activa'], name='SUSCRIPCION_posicio_6e653e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('usuario', 'posicion', 'tipo'), name='uniq_suscripcion_activa_usuario_posicion_tipo')],
            },
        ),
    ]
