# Generated by Django 6.0.4 on 2026-08-07 02:48

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0042_suscripcionnotificacionposicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcionnotificacionposicion',
            name='detalle_enviado',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
