# Generated by Django 6.0.4 on 2026-08-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0043_suscripcionnotificacionposicion_detalle_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='movpos',
            name='fecha_ocupacion',
            field=models.DateField(blank=True, db_column='FECHA_OCUPACION', null=True),
        ),
        migrations.AddField(
            model_name='movpos',
            name='id_registro_des_fecha_ocupacion',
            field=models.BigIntegerField(blank=True, db_column='ID_REGISTRO_DES_FECHA_OCUPACION', null=True),
        ),
        migrations.AddField(
            model_name='movposhistorico',
            name='fecha_ocupacion',
            field=models.DateField(blank=True, db_column='FECHA_OCUPACION', null=True),
        ),
        migrations.AddField(
            model_name='movposhistorico',
            name='id_registro_des_fecha_ocupacion',
            field=models.BigIntegerField(blank=True, db_column='ID_REGISTRO_DES_FECHA_OCUPACION', null=True),
        ),
        migrations.AddField(
            model_name='movposstaging',
            name='fecha_ocupacion',
            field=models.DateField(blank=True, db_column='FECHA_OCUPACION', null=True),
        ),
        migrations.AddField(
            model_name='movposstaging',
            name='id_registro_des_fecha_ocupacion',
            field=models.BigIntegerField(blank=True, db_column='ID_REGISTRO_DES_FECHA_OCUPACION', null=True),
        ),
    ]
