# Generated by Django 6.0.4 on 2026-08-13 01:25

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0044_movpos_fecha_ocupacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltroGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vista', models.CharField(db_index=True, max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('condiciones', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtros_guardados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'FILTRO_GUARDADO',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['usuario', 'vista'], name='FILTRO_GUAR_usuario_0ea5c6_idx')],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'vista', 'nombre'), name='uniq_filtro_guardado_usuario_vista_nombre')],
            },
        ),
    ]
