# Generated by Django 6.0.4 on 2026-08-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0045_filtroguardado'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(db_index=True, max_length=255, unique=True)),
                ('latitud', models.CharField(max_length=12)),
                ('longitud', models.CharField(max_length=13)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'GEOCODE_CACHE',
                'managed': True,
            },
        ),
    ]
