# Generated by Django 6.0.4 on 2026-08-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0046_geocodecache'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuscripcionApiControlPlazas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField(max_length=500)),
                ('token', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'SUSCRIPCION_API_CONTROL_PLAZAS',
                'ordering': ['nombre'],
            },
        ),
    ]
