# Generated by Django 6.0.7 on 2026-08-20 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0046_geocodecache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuenciaAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filas', models.JSONField(default=list)),
                ('unidad_administrativa', models.TextField(blank=True, default='')),
                ('justificacion', models.TextField(blank=True, default='')),
                ('firma_nombre', models.CharField(blank=True, default='Claudia Elizabeth De La Vega Madrigal', max_length=255)),
                ('firma_puesto', models.CharField(blank=True, default='Directora de Recursos Humanos', max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('generado_en', models.DateTimeField(blank=True, null=True)),
                ('veces_generado', models.PositiveIntegerField(default=0)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anexos_anuencia_modificados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anexos_anuencia_creados', to=settings.AUTH_USER_MODEL)),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anexos_anuencia_generados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anexo de Anuencia',
                'verbose_name_plural': 'Anexos de Anuencia',
                'ordering': ['-actualizado_en'],
            },
        ),
    ]
