# Generated by Django 6.0.7 on 2026-08-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0047_anuenciaanexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuenciaanexo',
            name='nombre_archivo',
            field=models.CharField(blank=True, default='Anexo 2 solicitud de ocupación de plazas', max_length=255),
        ),
        migrations.AlterField(
            model_name='anuenciaanexo',
            name='firma_nombre',
            field=models.CharField(blank=True, default='Nombre y Firma de la DRH', max_length=255),
        ),
    ]
