# Generated by Django 6.0.7 on 2026-08-20 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0049_anuenciaanexo_hojas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuenciaJustificacionCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('texto', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='justificaciones_anuencia_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Justificación de Anuencia (catálogo)',
                'verbose_name_plural': 'Justificaciones de Anuencia (catálogo)',
                'ordering': ['nombre'],
            },
        ),
    ]
