# Generated by Django 6.0.7 on 2026-08-28 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0050_anuenciajustificacioncatalogo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuenciaAnexo3Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('overrides', models.JSONField(blank=True, default=dict)),
                ('reasignaciones', models.JSONField(blank=True, default=dict)),
                ('grupos', models.JSONField(blank=True, default=list)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anexo3_versiones_modificadas', to=settings.AUTH_USER_MODEL)),
                ('anexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexo3_versiones', to='plantilla.anuenciaanexo')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anexo3_versiones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versión de Anexo 3',
                'verbose_name_plural': 'Versiones de Anexo 3',
                'ordering': ['-actualizado_en'],
                'constraints': [models.UniqueConstraint(fields=('anexo', 'nombre'), name='uniq_anexo3_version_nombre_por_anexo')],
            },
        ),
    ]
