# Generated by Django 6.0.7 on 2026-08-29 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0047_suscripcionapicontrolplazas'),
        ('plantilla', '0051_anuenciaanexo3version'),
    ]

    operations = [
    ]
