# Generated by Django 5.2.15 on 2026-09-03 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0053_anuenciaanexo_eliminado_anuenciaanexo_eliminado_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuenciaAnexoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cambios', models.JSONField(default=list)),
                ('anexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='plantilla.anuenciaanexo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cambio de Anexo de Anuencia',
                'verbose_name_plural': 'Cambios de Anexo de Anuencia',
                'ordering': ['-fecha'],
            },
        ),
    ]
