# Generated by Django 6.0.4 on 2026-07-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_whitelist_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_ocupacion_plazas', 'Puede ver Ocupación de Plazas por Oficio'), ('view_valuacion_presupuestaria', 'Puede ver Valuación Presupuestaria'), ('view_plantilla_empleados', 'Puede ver Plantilla de Empleados'), ('edit_plantilla_empleados', 'Puede editar Plantilla de Empleados'), ('view_oficios_turnados', 'Puede ver Oficios Turnados DO'), ('edit_oficios_turnados', 'Puede editar Oficios Turnados DO'), ('view_organigrama', 'Puede ver Organigrama ANAM'), ('view_monitoreo_zafiro', 'Puede ver Monitoreo ZAFIRO'), ('manage_roles', 'Puede administrar roles y permisos'), ('manage_usuarios', 'Puede administrar usuarios (whitelist)')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
