# Generated by Django 6.0.4 on 2026-07-12 04:48

from django.db import migrations

# Codenames que salieron del catálogo (reemplazados por permisos por-tab o
# eliminados por no tener ninguna acción real que gatear). Se limpian de
# auth_permission para que no aparezcan como basura en el catálogo de la UI de
# roles — verificado antes de escribir esto que ningún Group tenía estos
# permisos asignados todavía.
STALE_CODENAMES = [
    "view_ocupacion_plazas",
    "view_plantilla_empleados",
    "edit_plantilla_empleados",
    "edit_oficios_turnados",
]


def delete_stale_permissions(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    try:
        content_type = ContentType.objects.get(app_label="authentication", model="modulepermission")
    except ContentType.DoesNotExist:
        # Instalación nueva: el catálogo viejo nunca existió, nada que limpiar.
        return
    Permission.objects.filter(content_type=content_type, codename__in=STALE_CODENAMES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_role_permission_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulepermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_plantilla_detalle', 'Plantilla de Empleados: ver tab Detalle'), ('view_plantilla_estatus_nomina', 'Plantilla de Empleados: ver tab Estatus Nómina'), ('view_plantilla_mov_posiciones', 'Plantilla de Empleados: ver tab Mov. Posiciones'), ('view_plantilla_movimientos', 'Plantilla de Empleados: ver tab Movimientos'), ('view_plantilla_bajas', 'Plantilla de Empleados: ver tab Empleados Bajas'), ('view_plantilla_geografia', 'Plantilla de Empleados: ver tab Distribución Geográfica'), ('view_plantilla_catalogos', 'Plantilla de Empleados: ver tab Catálogos'), ('view_ocupacion_sankey', 'Ocupación de Plazas: ver tab Sankey'), ('view_ocupacion_tabla', 'Ocupación de Plazas: ver tab Tabla'), ('view_ocupacion_estadisticas', 'Ocupación de Plazas: ver tab Estadísticas'), ('edit_ocupacion_plazas', 'Ocupación de Plazas: editar asignación de plazas'), ('view_valuacion_presupuestaria', 'Valuación Presupuestaria: ver Simulador y Asuntos'), ('edit_valuacion_parametros', 'Valuación Presupuestaria: editar Parámetros (catálogo/conceptos/constantes)'), ('view_oficios_turnados', 'Puede ver Oficios Turnados DO'), ('view_organigrama', 'Puede ver Organigrama ANAM'), ('view_monitoreo_zafiro', 'Puede ver Monitoreo ZAFIRO'), ('manage_roles', 'Puede administrar roles y permisos'), ('manage_usuarios', 'Puede administrar usuarios (whitelist)')]},
        ),
        migrations.RunPython(delete_stale_permissions, migrations.RunPython.noop),
    ]
