# Generated by Django 6.0.4 on 2026-07-17 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_modulepermission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulepermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_plantilla_detalle', 'Plantilla de Empleados: ver tab Detalle'), ('view_plantilla_estatus_nomina', 'Plantilla de Empleados: ver tab Estatus Nómina'), ('view_plantilla_mov_posiciones', 'Plantilla de Empleados: ver tab Mov. Posiciones'), ('view_plantilla_movimientos', 'Plantilla de Empleados: ver tab Movimientos'), ('view_plantilla_bajas', 'Plantilla de Empleados: ver tab Empleados Bajas'), ('view_plantilla_geografia', 'Plantilla de Empleados: ver tab Distribución Geográfica'), ('view_plantilla_catalogos', 'Plantilla de Empleados: ver tab Catálogos'), ('edit_plantilla_detalle', 'Plantilla de Empleados: editar celdas en tab Detalle'), ('view_ocupacion_sankey', 'Ocupación de Plazas: ver tab Sankey'), ('view_ocupacion_tabla', 'Ocupación de Plazas: ver tab Tabla'), ('view_ocupacion_estadisticas', 'Ocupación de Plazas: ver tab Estadísticas'), ('edit_ocupacion_plazas', 'Ocupación de Plazas: editar asignación de plazas'), ('view_valuacion_presupuestaria', 'Valuación Presupuestaria: ver Simulador y Asuntos'), ('edit_valuacion_parametros', 'Valuación Presupuestaria: editar Parámetros (catálogo/conceptos/constantes)'), ('view_oficios_turnados', 'Puede ver Oficios Turnados DO'), ('view_organigrama_institucional', 'Organigrama ANAM: ver Vista Institucional'), ('view_organigrama_alineacion', 'Organigrama ANAM: ver Vista Alineación'), ('edit_organigrama', 'Organigrama ANAM: crear/editar/eliminar nodos (departamentos)'), ('view_monitoreo_zafiro', 'Puede ver Monitoreo ZAFIRO'), ('manage_roles', 'Puede administrar roles y permisos'), ('manage_usuarios', 'Puede administrar usuarios (whitelist)')]},
        ),
    ]
