# Generated by Django 6.0.7 on 2026-07-26 02:46

from django.db import migrations

# (base_codename, foto_codename, foto_name) — un permiso de foto nuevo por
# cada tab que ya muestra la tabla de empleados correspondiente.
FOTO_PERMISSION_PAIRS = [
    ("view_plantilla_detalle", "view_plantilla_detalle_foto", "Plantilla de Empleados: ver fotografía en tab Detalle"),
    ("view_plantilla_estatus_nomina", "view_plantilla_estatus_nomina_foto", "Plantilla de Empleados: ver fotografía en tab Estatus Nómina"),
    ("view_plantilla_mov_posiciones", "view_plantilla_mov_posiciones_foto", "Plantilla de Empleados: ver fotografía en tab Mov. Posiciones"),
    ("view_plantilla_movimientos", "view_plantilla_movimientos_foto", "Plantilla de Empleados: ver fotografía en tab Movimientos"),
    ("view_plantilla_bajas", "view_plantilla_bajas_foto", "Plantilla de Empleados: ver fotografía en tab Empleados Bajas"),
    ("view_plantilla_geografia", "view_plantilla_geografia_foto", "Plantilla de Empleados: ver fotografía en tab Distribución Geográfica"),
]


def backfill_foto_permissions(apps, schema_editor):
    # post_migrate (que normalmente crearía estos Permission a partir de
    # Meta.permissions) corre DESPUÉS de todas las migraciones de este
    # `migrate`, así que no se puede asumir que ya existen — se crean aquí
    # explícitamente antes de usarlos.
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    Group = apps.get_model("auth", "Group")

    content_type, _ = ContentType.objects.get_or_create(
        app_label="authentication", model="modulepermission"
    )

    foto_perm_by_base = {}
    for base_codename, foto_codename, foto_name in FOTO_PERMISSION_PAIRS:
        foto_perm, _ = Permission.objects.get_or_create(
            content_type=content_type, codename=foto_codename, defaults={"name": foto_name},
        )
        foto_perm_by_base[base_codename] = foto_perm

    # Todo rol que ya tenía el permiso base (ej. view_plantilla_detalle)
    # recibe también el nuevo _foto correspondiente, para no perder acceso a
    # fotografías que hoy sí ve — el toggle queda disponible para
    # deshabilitar desde ahora en adelante, sin regresión silenciosa.
    for group in Group.objects.prefetch_related("permissions").all():
        group_codenames = set(
            group.permissions.filter(content_type=content_type).values_list("codename", flat=True)
        )
        for base_codename, foto_perm in foto_perm_by_base.items():
            if base_codename in group_codenames:
                group.permissions.add(foto_perm)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_modulepermission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulepermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_plantilla_detalle', 'Plantilla de Empleados: ver tab Detalle'), ('view_plantilla_estatus_nomina', 'Plantilla de Empleados: ver tab Estatus Nómina'), ('view_plantilla_mov_posiciones', 'Plantilla de Empleados: ver tab Mov. Posiciones'), ('edit_plantilla_mov_posiciones', 'Plantilla de Empleados: editar Fecha de Anuencia en tab Mov. Posiciones'), ('view_plantilla_movimientos', 'Plantilla de Empleados: ver tab Movimientos'), ('view_plantilla_bajas', 'Plantilla de Empleados: ver tab Empleados Bajas'), ('view_plantilla_geografia', 'Plantilla de Empleados: ver tab Distribución Geográfica'), ('view_plantilla_catalogos', 'Plantilla de Empleados: ver tab Catálogos'), ('edit_plantilla_detalle', 'Plantilla de Empleados: editar celdas en tab Detalle'), ('view_plantilla_detalle_foto', 'Plantilla de Empleados: ver fotografía en tab Detalle'), ('view_plantilla_estatus_nomina_foto', 'Plantilla de Empleados: ver fotografía en tab Estatus Nómina'), ('view_plantilla_mov_posiciones_foto', 'Plantilla de Empleados: ver fotografía en tab Mov. Posiciones'), ('view_plantilla_movimientos_foto', 'Plantilla de Empleados: ver fotografía en tab Movimientos'), ('view_plantilla_bajas_foto', 'Plantilla de Empleados: ver fotografía en tab Empleados Bajas'), ('view_plantilla_geografia_foto', 'Plantilla de Empleados: ver fotografía en tab Distribución Geográfica'), ('view_ocupacion_sankey', 'Ocupación de Plazas: ver tab Sankey'), ('view_ocupacion_tabla', 'Ocupación de Plazas: ver tab Tabla'), ('view_ocupacion_estadisticas', 'Ocupación de Plazas: ver tab Estadísticas'), ('edit_ocupacion_plazas', 'Ocupación de Plazas: editar asignación de plazas'), ('view_valuacion_presupuestaria', 'Valuación Presupuestaria: ver Simulador y Asuntos'), ('edit_valuacion_parametros', 'Valuación Presupuestaria: editar Parámetros (catálogo/conceptos/constantes)'), ('view_oficios_turnados', 'Puede ver Oficios Turnados DO'), ('view_organigrama_institucional', 'Organigrama ANAM: ver Vista Institucional'), ('view_organigrama_alineacion', 'Organigrama ANAM: ver Vista Alineación'), ('view_organigrama_sig', 'Organigrama ANAM: ver Vista SIG'), ('edit_organigrama', 'Organigrama ANAM: crear/editar/eliminar nodos (departamentos)'), ('view_monitoreo_zafiro', 'Puede ver Monitoreo ZAFIRO'), ('manage_roles', 'Puede administrar roles y permisos'), ('manage_usuarios', 'Puede administrar usuarios (whitelist)')]},
        ),
        migrations.RunPython(backfill_foto_permissions, migrations.RunPython.noop),
    ]
