# Generated by Django 6.0.4 on 2026-07-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_requestvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('path', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('subtab', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='requestvisit',
            name='authenticat_email_c641f1_idx',
        ),
        migrations.DeleteModel(
            name='RequestVisit',
        ),
        migrations.AddIndex(
            model_name='presencelog',
            index=models.Index(fields=['email', 'created_at'], name='authenticat_email_e2ff82_idx'),
        ),
    ]
