# Generated by Django 6.0.7 on 2026-07-28 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_plantilla_foto_permissions'),
        ('authentication', '0011_presencelog_and_more'),
    ]

    operations = [
    ]
