# Generated by Django 5.2.15 on 2026-08-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_edit_datos_personales_permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificationCode',
        ),
        migrations.AddField(
            model_name='whitelist',
            name='debe_cambiar_password',
            field=models.BooleanField(default=True),
        ),
    ]
