# Generated by Django 6.0.7 on 2026-08-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_password_inutilizable_usuarios_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelist',
            name='tablero',
            field=models.CharField(blank=True, choices=[('rh', 'Tablero RH')], max_length=50, null=True),
        ),
    ]
