# Generated by Django 6.0.4 on 2026-08-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_password_inutilizable_usuarios_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RumMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('path', models.CharField(db_index=True, max_length=255)),
                ('metric_name', models.CharField(db_index=True, max_length=16)),
                ('value', models.FloatField()),
                ('rating', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['metric_name', 'created_at'], name='authenticat_metric__53eac3_idx')],
            },
        ),
    ]
