# Generated by Django 6.0.7 on 2026-09-02 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_alter_modulepermission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulepermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_plantilla_detalle', 'Plantilla de Empleados: ver tab Detalle'), ('view_plantilla_estatus_nomina', 'Plantilla de Empleados: ver tab Estatus Nómina'), ('view_plantilla_mov_posiciones', 'Plantilla de Empleados: ver tab Mov. Posiciones'), ('edit_plantilla_mov_posiciones', 'Plantilla de Empleados: editar Fecha de Anuencia en tab Mov. Posiciones'), ('view_plantilla_movimientos', 'Plantilla de Empleados: ver tab Movimientos'), ('view_plantilla_bajas', 'Plantilla de Empleados: ver tab Empleados Bajas'), ('view_plantilla_geografia', 'Plantilla de Empleados: ver tab Distribución Geográfica'), ('view_plantilla_catalogos', 'Plantilla de Empleados: ver tab Catálogos'), ('edit_plantilla_detalle', 'Plantilla de Empleados: editar celdas en tab Detalle'), ('edit_datos_personales', 'Plantilla de Empleados: editar Escolaridad/Contacto/Domicilio en Datos Personales'), ('view_plantilla_historico', 'Plantilla de Empleados: consultar plantillas históricas (tab Detalle)'), ('view_anuencia_eliminados', 'Plantilla de Empleados: ver y reactivar Anexos 2 eliminados (Anuencia)'), ('view_plantilla_detalle_foto', 'Plantilla de Empleados: ver fotografía en tab Detalle'), ('view_plantilla_estatus_nomina_foto', 'Plantilla de Empleados: ver fotografía en tab Estatus Nómina'), ('view_plantilla_mov_posiciones_foto', 'Plantilla de Empleados: ver fotografía en tab Mov. Posiciones'), ('view_plantilla_movimientos_foto', 'Plantilla de Empleados: ver fotografía en tab Movimientos'), ('view_plantilla_bajas_foto', 'Plantilla de Empleados: ver fotografía en tab Empleados Bajas'), ('view_plantilla_geografia_foto', 'Plantilla de Empleados: ver fotografía en tab Distribución Geográfica'), ('view_ocupacion_sankey', 'Ocupación de Plazas: ver tab Sankey'), ('view_ocupacion_tabla', 'Ocupación de Plazas: ver tab Tabla'), ('view_ocupacion_estadisticas', 'Ocupación de Plazas: ver tab Estadísticas'), ('edit_ocupacion_plazas', 'Ocupación de Plazas: editar asignación de plazas'), ('view_valuacion_presupuestaria', 'Valuación Presupuestaria: ver Simulador y Asuntos'), ('edit_valuacion_parametros', 'Valuación Presupuestaria: editar Parámetros (catálogo/conceptos/constantes)'), ('view_oficios_turnados', 'Puede ver Oficios Turnados DO'), ('view_organigrama_institucional', 'Organigrama ANAM: ver Vista Institucional'), ('view_organigrama_alineacion', 'Organigrama ANAM: ver Vista Alineación'), ('view_organigrama_sig', 'Organigrama ANAM: ver Vista SIG'), ('edit_organigrama', 'Organigrama ANAM: crear/editar/eliminar nodos (departamentos)'), ('view_monitoreo_zafiro', 'Puede ver Monitoreo ZAFIRO'), ('manage_roles', 'Puede administrar roles y permisos'), ('manage_usuarios', 'Puede administrar usuarios (whitelist)')]},
        ),
    ]
