# Generated by Django 5.2.15 on 2026-09-14 19:27

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_alter_modulepermission_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelist',
            name='tablero',
            field=models.CharField(blank=True, choices=[('rh', 'Tablero RH'), ('personalizable', 'Tablero Personalizable')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='TableroLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widgets', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tablero_layout', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
