# Generated by Django 5.2.15 on 2026-09-24 20:20

from django.db import migrations

# Pestañas del modal de expediente (EmployeesModal), ahora con permiso propio.
PERMISOS_EXPEDIENTE = [
    ("view_expediente_plaza", "Expediente del personal: ver pestaña Expediente"),
    ("view_expediente_datos_personales", "Expediente del personal: ver pestaña Datos Personales"),
    ("view_expediente_historial_movimientos", "Expediente del personal: ver pestaña Historial de Movimientos"),
    ("view_expediente_historial_posicion", "Expediente del personal: ver pestaña Historial de Posición"),
]

# Permisos desde los que HOY se puede abrir el expediente: cualquier tab que
# liste empleados o plazas. Un rol con alguno de estos ya veía las 4 pestañas.
PERMISOS_QUE_ABREN_EXPEDIENTE = {
    "view_plantilla_detalle",
    "view_plantilla_estatus_nomina",
    "view_plantilla_mov_posiciones",
    "view_plantilla_movimientos",
    "view_plantilla_bajas",
    "view_plantilla_geografia",
}


def backfill_permisos_expediente(apps, schema_editor):
    # post_migrate (que normalmente crearía estos Permission a partir de
    # Meta.permissions) corre DESPUÉS de todas las migraciones de este
    # `migrate`, así que se crean aquí explícitamente antes de usarlos —
    # mismo patrón que 0010_plantilla_foto_permissions.
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    Group = apps.get_model("auth", "Group")

    content_type, _ = ContentType.objects.get_or_create(
        app_label="authentication", model="modulepermission"
    )

    nuevos = [
        Permission.objects.get_or_create(
            content_type=content_type, codename=codename, defaults={"name": nombre}
        )[0]
        for codename, nombre in PERMISOS_EXPEDIENTE
    ]

    # Todo rol que ya podía abrir el expediente recibe las 4 pestañas, para
    # que este cambio no le quite nada a nadie: el recorte por pestaña queda
    # disponible de aquí en adelante, desmarcando lo que no se quiera dar.
    for group in Group.objects.prefetch_related("permissions").all():
        codenames = set(
            group.permissions.filter(content_type=content_type).values_list("codename", flat=True)
        )
        if codenames & PERMISOS_QUE_ABREN_EXPEDIENTE:
            group.permissions.add(*nuevos)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_tablerolayout_escritorios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulepermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_plantilla_detalle', 'Plantilla de Empleados: ver tab Detalle'), ('view_plantilla_estatus_nomina', 'Plantilla de Empleados: ver tab Estatus Nómina'), ('view_plantilla_mov_posiciones', 'Plantilla de Empleados: ver tab Mov. Posiciones'), ('edit_plantilla_mov_posiciones', 'Plantilla de Empleados: editar Fecha de Anuencia en tab Mov. Posiciones'), ('view_plantilla_movimientos', 'Plantilla de Empleados: ver tab Movimientos'), ('view_plantilla_bajas', 'Plantilla de Empleados: ver tab Empleados Bajas'), ('view_plantilla_geografia', 'Plantilla de Empleados: ver tab Distribución Geográfica'), ('view_plantilla_catalogos', 'Plantilla de Empleados: ver tab Catálogos'), ('edit_plantilla_detalle', 'Plantilla de Empleados: editar celdas en tab Detalle'), ('edit_datos_personales', 'Plantilla de Empleados: editar Escolaridad/Contacto/Domicilio en Datos Personales'), ('view_plantilla_historico', 'Plantilla de Empleados: consultar plantillas históricas (tab Detalle)'), ('view_anuencia_eliminados', 'Plantilla de Empleados: ver y reactivar Anexos 2 eliminados (Anuencia)'), ('view_plantilla_detalle_foto', 'Plantilla de Empleados: ver fotografía en tab Detalle'), ('view_plantilla_estatus_nomina_foto', 'Plantilla de Empleados: ver fotografía en tab Estatus Nómina'), ('view_plantilla_mov_posiciones_foto', 'Plantilla de Empleados: ver fotografía en tab Mov. Posiciones'), ('view_plantilla_movimientos_foto', 'Plantilla de Empleados: ver fotografía en tab Movimientos'), ('view_plantilla_bajas_foto', 'Plantilla de Empleados: ver fotografía en tab Empleados Bajas'), ('view_plantilla_geografia_foto', 'Plantilla de Empleados: ver fotografía en tab Distribución Geográfica'), ('view_expediente_plaza', 'Expediente del personal: ver pestaña Expediente'), ('view_expediente_datos_personales', 'Expediente del personal: ver pestaña Datos Personales'), ('view_expediente_historial_movimientos', 'Expediente del personal: ver pestaña Historial de Movimientos'), ('view_expediente_historial_posicion', 'Expediente del personal: ver pestaña Historial de Posición'), ('view_ocupacion_sankey', 'Ocupación de Plazas: ver tab Sankey'), ('view_ocupacion_tabla', 'Ocupación de Plazas: ver tab Tabla'), ('view_ocupacion_estadisticas', 'Ocupación de Plazas: ver tab Estadísticas'), ('edit_ocupacion_plazas', 'Ocupación de Plazas: editar asignación de plazas'), ('view_ocupacion_solicitudes', 'Ocupación de Plazas: ver tabla de Solicitudes de Nueva Creación'), ('view_valuacion_presupuestaria', 'Valuación Presupuestaria: ver Simulador y Asuntos'), ('edit_valuacion_parametros', 'Valuación Presupuestaria: editar Parámetros (catálogo/conceptos/constantes)'), ('view_oficios_turnados', 'Puede ver Oficios Turnados DO'), ('view_organigrama_institucional', 'Organigrama ANAM: ver Vista Institucional'), ('view_organigrama_alineacion', 'Organigrama ANAM: ver Vista Alineación'), ('view_organigrama_sig', 'Organigrama ANAM: ver Vista SIG'), ('edit_organigrama', 'Organigrama ANAM: crear/editar/eliminar nodos (departamentos)'), ('view_monitoreo_zafiro', 'Puede ver Monitoreo ZAFIRO'), ('manage_roles', 'Puede administrar roles y permisos'), ('manage_usuarios', 'Puede administrar usuarios (whitelist)')]},
        ),
        migrations.RunPython(backfill_permisos_expediente, migrations.RunPython.noop),
    ]
