# Generated by Django 5.2.15 on 2026-09-28 19:39

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_alter_modulepermission_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoriaColumnas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(max_length=40)),
                ('slot', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(blank=True, default='', max_length=40)),
                ('columnas', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorias_columnas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'tabla', 'slot'), name='uniq_memoria_columnas_slot')],
            },
        ),
    ]
