# Generated by Django 6.0.8 on 2026-10-05 21:41

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0027_memoriacolumnas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RolUaScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_ua_codes', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ua_scope_config', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='RolPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('titular', 'Titular de unidad'), ('transversal', 'Transversal'), ('subrol', 'Subrol')], default='transversal', max_length=12)),
                ('cd_un', models.CharField(blank=True, max_length=5, null=True)),
                ('cd_ua', models.CharField(blank=True, max_length=3, null=True)),
                ('max_usuarios', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('es_sistema', models.BooleanField(default=False)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perfiles_hijos', to='auth.group')),
                ('rol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_rol', to='auth.group')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cd_un', 'cd_ua'), name='rolperfil_unidad_unica')],
            },
        ),
    ]
