# Generated by Django 6.0.8 on 2026-10-05 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_roluascope_rolperfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescargaExcelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('rol', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modulo', models.CharField(default='plantilla_detalle', max_length=60)),
                ('modo', models.CharField(default='actual', max_length=12)),
                ('fecha_historica', models.CharField(blank=True, default='', max_length=10)),
                ('total_filas', models.PositiveIntegerField(default=0)),
                ('columnas', models.JSONField(default=list)),
                ('filtros', models.JSONField(default=dict)),
                ('incluyo_fotos', models.BooleanField(default=False)),
                ('incluyo_datos_personales', models.BooleanField(default=False)),
                ('nombre_archivo', models.CharField(blank=True, default='', max_length=255)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('regenerada_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regeneraciones', to='authentication.descargaexcellog')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'created_at'], name='authenticat_email_cb374f_idx')],
            },
        ),
    ]
