# Generated by Django 6.0.8 on 2026-10-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_descargaexcellog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descargaexcellog',
            name='modulo',
            field=models.CharField(default='plantilla_detalle', max_length=200),
        ),
    ]
