# Generated by Django 6.0.8 on 2026-10-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0032_alter_modulepermission_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelist',
            name='terminos_aceptados_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whitelist',
            name='terminos_ip',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='whitelist',
            name='terminos_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
