# Generated by Django 6.0.4 on 2026-10-06 19:26

from django.db import migrations


# Tarjetas/filas del banner de plantillas históricas, ahora con permiso
# propio. "Plazas Activas" no tiene permiso propio (ver comentario en
# ModulePermission.Meta.permissions): es la implícita de
# view_plantilla_historico y no se puede revocar.
PERMISOS_HISTORICO_TARJETAS = [
    ("view_plantilla_historico_plazas_totales", "Plantilla de Empleados: mostrar tarjeta Plazas Totales (plantillas históricas)"),
    ("view_plantilla_historico_plazas_inactivas", "Plantilla de Empleados: mostrar plazas Inactivas (plantillas históricas, tarjeta y tabla)"),
    ("view_plantilla_historico_plazas_ocupadas", "Plantilla de Empleados: mostrar plazas Ocupadas (plantillas históricas, tarjeta y tabla)"),
    ("view_plantilla_historico_plazas_vacantes", "Plantilla de Empleados: mostrar plazas Vacantes (plantillas históricas, tarjeta y tabla)"),
]


def backfill_permisos_historico_tarjetas(apps, schema_editor):
    """Todo rol que hoy ve el modo histórico recibe sus 4 permisos nuevos,
    para que este cambio no le quite nada a nadie: el recorte por tarjeta/
    fila queda disponible de aquí en adelante. Mismo patrón que 0032 (los
    Permission se crean a mano porque post_migrate corre después)."""
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    Group = apps.get_model("auth", "Group")

    content_type, _ = ContentType.objects.get_or_create(
        app_label="authentication", model="modulepermission"
    )
    nuevos = [
        Permission.objects.get_or_create(
            content_type=content_type, codename=codename, defaults={"name": nombre}
        )[0]
        for codename, nombre in PERMISOS_HISTORICO_TARJETAS
    ]
    for group in Group.objects.filter(
        permissions__content_type=content_type, permissions__codename="view_plantilla_historico"
    ).distinct():
        group.permissions.add(*nuevos)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_whitelist_terminos_aceptados_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulepermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_plantilla_detalle', 'Plantilla de Empleados: ver tab Detalle'), ('view_plantilla_estatus_nomina', 'Plantilla de Empleados: ver tab Estatus Nómina'), ('view_plantilla_mov_posiciones', 'Plantilla de Empleados: ver tab Mov. Posiciones'), ('edit_plantilla_mov_posiciones', 'Plantilla de Empleados: editar Fecha de Anuencia en tab Mov. Posiciones'), ('view_plantilla_movimientos', 'Plantilla de Empleados: ver tab Movimientos'), ('view_plantilla_bajas', 'Plantilla de Empleados: ver tab Empleados Bajas'), ('view_plantilla_geografia', 'Plantilla de Empleados: ver tab Distribución Geográfica'), ('view_plantilla_geografia_mapa', 'Plantilla de Empleados: ver sub-tab Mapa Nacional (Distribución Geográfica)'), ('view_plantilla_geografia_torre', 'Plantilla de Empleados: ver sub-tab Torre Caballito (Distribución Geográfica)'), ('view_plantilla_catalogos', 'Plantilla de Empleados: ver tab Catálogos'), ('view_plantilla_mov_posiciones_tabla', 'Plantilla de Empleados: ver sub-tab Tabla Principal (Mov. Posiciones)'), ('view_plantilla_mov_posiciones_cuadros', 'Plantilla de Empleados: ver sub-tab Cuadros Vacancia (Mov. Posiciones)'), ('view_plantilla_mov_posiciones_alineacion', 'Plantilla de Empleados: ver sub-tab Comprobar Alineación (Mov. Posiciones)'), ('view_plantilla_mov_posiciones_aduanas', 'Plantilla de Empleados: ver sub-tab Aduanas Ocupación vs Vacantes (Mov. Posiciones)'), ('view_plantilla_mov_posiciones_anuencia', 'Plantilla de Empleados: ver sub-tab Anuencia (Mov. Posiciones)'), ('edit_plantilla_detalle', 'Plantilla de Empleados: editar celdas en tab Detalle'), ('edit_datos_personales', 'Plantilla de Empleados: editar Escolaridad/Contacto/Domicilio en Datos Personales'), ('view_plantilla_historico', 'Plantilla de Empleados: consultar plantillas históricas (tab Detalle)'), ('view_plantilla_historico_plazas_totales', 'Plantilla de Empleados: mostrar tarjeta Plazas Totales (plantillas históricas)'), ('view_plantilla_historico_plazas_inactivas', 'Plantilla de Empleados: mostrar plazas Inactivas (plantillas históricas, tarjeta y tabla)'), ('view_plantilla_historico_plazas_ocupadas', 'Plantilla de Empleados: mostrar plazas Ocupadas (plantillas históricas, tarjeta y tabla)'), ('view_plantilla_historico_plazas_vacantes', 'Plantilla de Empleados: mostrar plazas Vacantes (plantillas históricas, tarjeta y tabla)'), ('view_plantilla_switch_oficial', 'Plantilla de Empleados: usar el switch Plantilla Oficial (tab Detalle)'), ('view_anuencia_eliminados', 'Plantilla de Empleados: ver y reactivar Anexos 2 eliminados (Anuencia)'), ('view_plantilla_detalle_foto', 'Plantilla de Empleados: ver fotografía en tab Detalle'), ('view_plantilla_estatus_nomina_foto', 'Plantilla de Empleados: ver fotografía en tab Estatus Nómina'), ('view_plantilla_mov_posiciones_foto', 'Plantilla de Empleados: ver fotografía en tab Mov. Posiciones'), ('view_plantilla_movimientos_foto', 'Plantilla de Empleados: ver fotografía en tab Movimientos'), ('view_plantilla_bajas_foto', 'Plantilla de Empleados: ver fotografía en tab Empleados Bajas'), ('view_plantilla_geografia_foto', 'Plantilla de Empleados: ver fotografía en tab Distribución Geográfica'), ('view_expediente_plaza', 'Expediente del personal: ver pestaña Expediente'), ('view_expediente_datos_personales', 'Expediente del personal: ver pestaña Datos Personales'), ('view_expediente_historial_movimientos', 'Expediente del personal: ver pestaña Historial de Movimientos'), ('view_expediente_historial_posicion', 'Expediente del personal: ver pestaña Historial de Posición'), ('view_ocupacion_sankey', 'Ocupación de Plazas: ver tab Sankey'), ('view_ocupacion_tabla', 'Ocupación de Plazas: ver tab Tabla'), ('view_ocupacion_estadisticas', 'Ocupación de Plazas: ver tab Estadísticas'), ('edit_ocupacion_plazas', 'Ocupación de Plazas: editar asignación de plazas'), ('view_ocupacion_solicitudes', 'Ocupación de Plazas: ver tabla de Solicitudes de Nueva Creación'), ('view_valuacion_presupuestaria', 'Valuación Presupuestaria: ver Simulador y Asuntos'), ('edit_valuacion_parametros', 'Valuación Presupuestaria: editar Parámetros (catálogo/conceptos/constantes)'), ('view_oficios_turnados', 'Puede ver Oficios Turnados DO'), ('view_organigrama_institucional', 'Organigrama ANAM: ver Vista Institucional'), ('view_organigrama_alineacion', 'Organigrama ANAM: ver Vista Alineación'), ('view_organigrama_sig', 'Organigrama ANAM: ver Vista SIG'), ('edit_organigrama', 'Organigrama ANAM: crear/editar/eliminar nodos (departamentos)'), ('view_monitoreo_zafiro', 'Puede ver Monitoreo ZAFIRO'), ('manage_roles', 'Puede administrar roles y permisos'), ('manage_usuarios', 'Puede administrar usuarios (whitelist)')]},
        ),
        migrations.RunPython(backfill_permisos_historico_tarjetas, migrations.RunPython.noop),
    ]
