from django.urls import path

from .views import (
    TorreCaballitoSearchView,
    EmpleadosPorNivelYEstatusView,
    ExportExcelView,
    OcupacionPorOficiosResumenView,
    Plantilla1800PlazasListView,
    PlantillaVacantesPorNivelResumenView,
    PlantillaVacantesPorNivelView,
    RegistrosPorOficio1800PlazasView,
    EmpleadosCompletosEstatusNominaResumenView,
    EmpleadosCompletosActivosDetalleView,
    EmpleadosEstatusPorNivelUaView,
    EmpleadosDistribucionGeograficaView,
    MovPosAlineacionView,
    MovPosDetalleView,
    MovPosExportExcelView,
    MovPosHistoriaView,
    MovPosVacanciaDetalleView,
    CadenaMandoView,
    ZafiroBitacoraView,
    UltimaActualizacionZafiroView,
    IniciarSincronizacionZafiroView,
    ZafiroSSEView,
    BajasSigListView,
    BajasMotivosPieView,
    BajasHistoricoView,
    ExportarEstatusExcelView,
    OrganigramaSearchView,
    TorreCaballito3DView,
    TorreCaballitoEmpleadosView,
    MovimientosPersonalListView,
    MovimientosPersonalStatsView,
    MovimientosPersonalHistorialView,
    OrganigramaDeptoView,
    OrganigramaTreeView,
    OrganigramaPosicionInfoView,
    CatAccionesViewSet,
    CatAccionesMotivosViewSet,
    CatNivelJerarquicoPlazaViewSet,
    CatPtoFuncViewSet,
    RcCatCodPresupuestalViewSet,
    CuadroVacanciaView,
    DesgloseJerarquicoView,
    DesgloseJerarquicoOcupadosView,
)

urlpatterns = [
    path(
        "movimientos-personal/",
        MovimientosPersonalListView.as_view(),
        name="movimientos-personal",
    ),
    path(
        "movimientos-personal/stats/",
        MovimientosPersonalStatsView.as_view(),
        name="movimientos-personal-stats",
    ),
    path(
        "movimientos-personal/historial/",
        MovimientosPersonalHistorialView.as_view(),
        name="movimientos-personal-historial",
    ),
    path(
        "organigrama-deptos/",
        OrganigramaDeptoView.as_view(),
        name="organigrama-deptos",
    ),
    path(
        "organigrama-tree/",
        OrganigramaTreeView.as_view(),
        name="organigrama-tree",
    ),
    path(
        "organigrama-posicion-info/",
        OrganigramaPosicionInfoView.as_view(),
        name="organigrama-posicion-info",
    ),
    path(
        "cat-acciones/",
        CatAccionesViewSet.as_view({"get": "list", "post": "create"}),
        name="cat-acciones",
    ),
    path(
        "cat-acciones/<str:pk>/",
        CatAccionesViewSet.as_view(
            {"put": "update", "patch": "partial_update", "delete": "destroy"}
        ),
        name="cat-acciones-detail",
    ),
    path(
        "cat-acciones-motivos/",
        CatAccionesMotivosViewSet.as_view({"get": "list", "post": "create"}),
        name="cat-acciones-motivos",
    ),
    path(
        "cat-acciones-motivos/<int:pk>/",
        CatAccionesMotivosViewSet.as_view(
            {"put": "update", "patch": "partial_update", "delete": "destroy"}
        ),
        name="cat-acciones-motivos-detail",
    ),
    path(
        "cat-pto-func/",
        CatPtoFuncViewSet.as_view({"get": "list", "post": "create"}),
        name="cat-pto-func",
    ),
    path(
        "cat-pto-func/<int:pk>/",
        CatPtoFuncViewSet.as_view(
            {"put": "update", "patch": "partial_update", "delete": "destroy"}
        ),
        name="cat-pto-func-detail",
    ),
    path(
        "cat-cod-presupuestal/",
        RcCatCodPresupuestalViewSet.as_view({"get": "list", "post": "create"}),
        name="cat-cod-presupuestal",
    ),
    path(
        "cat-cod-presupuestal/<str:codigo_presupuestal>/<int:escala>/",
        RcCatCodPresupuestalViewSet.as_view(
            {"put": "update", "patch": "partial_update", "delete": "destroy"}
        ),
        name="cat-cod-presupuestal-detail",
    ),
    path(
        "cat-nivel-jerarquico-plaza/niveles/",
        CatNivelJerarquicoPlazaViewSet.as_view({"get": "niveles"}),
        name="cat-nivel-jerarquico-plaza-niveles",
    ),
    path(
        "cat-nivel-jerarquico-plaza/bulk-assign/",
        CatNivelJerarquicoPlazaViewSet.as_view({"post": "bulk_assign"}),
        name="cat-nivel-jerarquico-plaza-bulk-assign",
    ),
    path(
        "cat-nivel-jerarquico-plaza/prioridad/",
        CatNivelJerarquicoPlazaViewSet.as_view({"get": "prioridad"}),
        name="cat-nivel-jerarquico-plaza-prioridad",
    ),
    path(
        "cat-nivel-jerarquico-plaza/aplicar-prioridad/",
        CatNivelJerarquicoPlazaViewSet.as_view({"post": "aplicar_prioridad"}),
        name="cat-nivel-jerarquico-plaza-aplicar-prioridad",
    ),
    path(
        "cat-nivel-jerarquico-plaza/",
        CatNivelJerarquicoPlazaViewSet.as_view({"get": "list", "post": "create"}),
        name="cat-nivel-jerarquico-plaza",
    ),
    path(
        "cat-nivel-jerarquico-plaza/<str:pk>/",
        CatNivelJerarquicoPlazaViewSet.as_view(
            {"put": "update", "patch": "partial_update", "delete": "destroy"}
        ),
        name="cat-nivel-jerarquico-plaza-detail",
    ),
    path(
        "torre-caballito/",
        TorreCaballito3DView.as_view(),
        name="torre-caballito",
    ),
    path(
        "torre-caballito/empleados/",
        TorreCaballitoEmpleadosView.as_view(),
        name="torre-caballito-empleados",
    ),
    path(
        "torre-caballito/search/",
        TorreCaballitoSearchView.as_view(),
        name="torre-caballito-search",
    ),
    path(
        "bitacora/sse/",
        ZafiroSSEView.as_view(),
        name="zafiro_bitacora_sse",
    ),
    path(
        "bitacora/ultima/",
        UltimaActualizacionZafiroView.as_view(),
        name="zafiro_bitacora_ultima",
    ),
    path(
        "bitacora/iniciar/",
        IniciarSincronizacionZafiroView.as_view(),
        name="zafiro_iniciar_sincronizacion",
    ),
    path(
        "bitacora/",
        ZafiroBitacoraView.as_view(),
        name="zafiro_bitacora",
    ),
    path(
        "export/excel/",
        ExportExcelView.as_view(),
        name="export_excel",
    ),
    path(
        "estatus_nomina_por_nivel/",
        PlantillaVacantesPorNivelView.as_view(),
        name="estatus_nomina_por_nivel",
    ),
    path(
        "estatus_nomina_por_nivel/resumen/",
        PlantillaVacantesPorNivelResumenView.as_view(),
        name="estatus_nomina_por_nivel_resumen",
    ),
    path(
        "empleados_completos_estatus_resumen/",
        EmpleadosCompletosEstatusNominaResumenView.as_view(),
        name="empleados_completos_estatus_resumen",
    ),
    path(
        "empleados_completos_activos_detalle/",
        EmpleadosCompletosActivosDetalleView.as_view(),
        name="empleados_completos_activos_detalle",
    ),
    path(
        "empleados_por_nivel_y_estatus/",
        EmpleadosPorNivelYEstatusView.as_view(),
        name="empleados_por_nivel_y_estatus",
    ),
    path(
        "exportar_estatus_excel/",
        ExportarEstatusExcelView.as_view(),
        name="exportar_estatus_excel",
    ),
    path(
        "ocupacion_por_oficios_resumen/",
        OcupacionPorOficiosResumenView.as_view(),
        name="ocupacion_por_oficios_resumen",
    ),
    path(
        "registros_por_oficio_1800_plazas/",
        RegistrosPorOficio1800PlazasView.as_view(),
        name="registros_por_oficio_1800_plazas",
    ),
    path(
        "plantilla_1800_plazas_list/",
        Plantilla1800PlazasListView.as_view(),
        name="plantilla_1800_plazas_list",
    ),
    path(
        "empleados_estatus_por_nivel_ua/",
        EmpleadosEstatusPorNivelUaView.as_view(),
        name="empleados_estatus_por_nivel_ua",
    ),
    path(
        "empleados_distribucion_geografica/",
        EmpleadosDistribucionGeograficaView.as_view(),
        name="empleados_distribucion_geografica",
    ),
    path(
        "mov_pos_detalle/export_excel/",
        MovPosExportExcelView.as_view(),
        name="mov_pos_export_excel",
    ),
    path(
        "mov_pos_detalle/",
        MovPosDetalleView.as_view(),
        name="mov_pos_detalle",
    ),
    path(
        "mov_pos_historia/",
        MovPosHistoriaView.as_view(),
        name="mov_pos_historia",
    ),
    path(
        "mov_pos_vacancia_detalle/",
        MovPosVacanciaDetalleView.as_view(),
        name="mov_pos_vacancia_detalle",
    ),
    path(
        "mov_pos_alineacion/",
        MovPosAlineacionView.as_view(),
        name="mov_pos_alineacion",
    ),
    path(
        "cadena_mando/",
        CadenaMandoView.as_view(),
        name="cadena_mando",
    ),
    path(
        "bajas_sig/",
        BajasSigListView.as_view(),
        name="bajas_sig",
    ),
    path(
        "bajas_sig/motivos/",
        BajasMotivosPieView.as_view(),
        name="bajas_sig_motivos",
    ),
    path(
        "bajas_sig/historico/",
        BajasHistoricoView.as_view(),
        name="bajas_sig_historico",
    ),
    path(
        "organigrama_search/",
        OrganigramaSearchView.as_view(),
        name="organigrama_search",
    ),
    path(
        "cuadro_vacancia/",
        CuadroVacanciaView.as_view(),
        name="cuadro_vacancia",
    ),
    path(
        "desglose_jerarquico/",
        DesgloseJerarquicoView.as_view(),
        name="desglose_jerarquico",
    ),
    path(
        "desglose_jerarquico_ocupados/",
        DesgloseJerarquicoOcupadosView.as_view(),
        name="desglose_jerarquico_ocupados",
    ),
]
