# Generated by Django 6.0.4 on 2026-09-14 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_tipo_oficio', '0003_asuntovaluacion_oficio_resolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asuntovaluacion',
            name='oficio_notificacion_ocupacion',
            field=models.FileField(blank=True, null=True, upload_to='oficios/notificacion_ocupacion/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Oficio de Notificación de Ocupación (PDF)'),
        ),
    ]
